- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - openjdk-8-jdk
      - python3
      - python-apt

- name: "Check status of Hadoop directory"
  stat:
    path: "{{hadoop_base}}"
  register: stat_exist_dir_hadoop

- name: "Get files - Hadoop verion 3.2.1"
  unarchive:
    src: "{{mirror_ftp}}"
    dest: "{{hadoop_base}}"
    owner: "{{user_name}}"
    group: "{{user_name}}"
    remote_src: yes
  when: stat_exist_dir_hadoop.stat.isdir
